# Generated by Django 4.0.5 on 2022-06-23 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_base_room'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Room',
            new_name='base',
        ),
    ]
