# Generated by Django 4.0.5 on 2022-06-23 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_room_base'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='base',
            new_name='Room',
        ),
    ]
