# Generated by Django 4.0.5 on 2022-06-28 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename_base_room'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Room',
            new_name='Books',
        ),
    ]
