# Generated by Django 4.0.5 on 2022-07-01 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_topic_books_host_message_books_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='host',
        ),
        migrations.RemoveField(
            model_name='books',
            name='topic',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
