# Generated by Django 4.0.5 on 2022-07-01 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_remove_books_host_remove_books_topic_delete_message_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Books',
            new_name='Book',
        ),
    ]
