# Generated by Django 4.0.5 on 2022-07-19 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_rename_books_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=50)),
                ('SecondName', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=200)),
                ('Confirmpassword', models.CharField(max_length=50)),
            ],
        ),
    ]
