# Generated by Django 4.0.5 on 2022-07-24 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_member_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
    ]
