# Generated by Django 4.0.5 on 2022-08-24 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_available'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Available',
        ),
    ]
