# Generated by Django 3.0.5 on 2022-06-28 18:51

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.TextField(max_length=120)),
                ('title', models.TextField(max_length=120)),
                ('author', models.TextField(max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_of_publication', models.DateField(blank=True, null=True)),
                ('subject_area', models.TextField()),
                ('uploaded_by', models.TextField(blank=True, max_length=120, null=True)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='A_library/pdfs/')),
                ('Featured', models.BooleanField(default=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Borrowers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.TextField(blank=True, max_length=120, null=True)),
                ('Featured', models.BooleanField(default=True, null=True)),
                ('date_borrowed', models.DateField(max_length=120)),
                ('date_returned', models.DateField(max_length=120)),
                ('book_id', models.TextField()),
                ('expected_date_return', models.DateField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.TextField(max_length=120)),
                ('fine_ammount', models.TextField(max_length=120)),
                ('payment', models.TextField(blank=True, null=True)),
                ('book_id', models.TextField()),
                ('student_id', models.TextField(blank=True, max_length=120, null=True)),
                ('uploaded_by', models.TextField(blank=True, max_length=120, null=True)),
                ('Featured', models.BooleanField(default=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.TextField(blank=True, max_length=120, null=True)),
                ('student_name', models.TextField(blank=True, null=True)),
                ('registration_no', models.TextField(max_length=120)),
                ('Featured', models.BooleanField(default=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_Librarian', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'swappable': 'AUTH_USER_MODEL',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
