# Generated by Django 3.0.5 on 2022-06-28 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Borrowers',
            new_name='Borrower',
        ),
        migrations.RenameModel(
            old_name='Payments',
            new_name='Payment',
        ),
        migrations.RenameModel(
            old_name='Students',
            new_name='Student',
        ),
    ]
