# Generated by Django 3.0.5 on 2022-06-28 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20220628_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='sex',
            field=models.TextField(blank=True, null=True),
        ),
    ]
