# Generated by Django 3.0.5 on 2022-06-29 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_student_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.TextField(help_text='Enter field documentation', max_length=120),
        ),
    ]
