# Generated by Django 3.0.5 on 2022-06-29 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20220629_1257'),
    ]

    operations = [
        migrations.CreateModel(
            name='book_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('b', 'borrowed'), ('a', 'Available'), ('r', 'Reserved')], default='b', help_text='Book availability', max_length=120)),
            ],
        ),
    ]
