# Generated by Django 3.0.5 on 2022-06-29 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_book_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='book_status',
        ),
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(blank=True, choices=[('b', 'borrowed'), ('a', 'Available'), ('r', 'Reserved')], default='b', help_text='Book availability', max_length=120),
        ),
    ]
