# Generated by Django 3.0.5 on 2022-06-29 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20220629_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='sex',
        ),
    ]
