# Generated by Django 3.0.5 on 2022-06-29 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_auto_20220629_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='base',
            field=models.CharField(blank=True, choices=[('F', 'Female'), ('M', 'Male')], default='b', max_length=1),
        ),
    ]
