# Generated by Django 3.0.5 on 2022-06-29 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_student_base'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='base',
            new_name='gender',
        ),
    ]
