# Generated by Django 3.0.5 on 2022-06-29 21:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_auto_20220629_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrower',
            name='id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AlterField(
            model_name='borrower',
            name='student_id',
            field=models.TextField(blank=True, max_length=120, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='book_id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular book across whole library'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.TextField(auto_created=True, max_length=120, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.TextField(blank=True, max_length=120, primary_key=True, serialize=False),
        ),
    ]
