# Generated by Django 3.0.5 on 2022-06-29 21:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_auto_20220630_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower',
            name='book_id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular book across whole library'),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='student_id',
            field=models.TextField(default=True, max_length=120, primary_key=True, serialize=False),
        ),
    ]
