# Generated by Django 3.0.5 on 2022-06-30 16:55

import catalog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_auto_20220630_1207'),
    ]

    operations = [
        migrations.CreateModel(
            name='Siteuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100, validators=[catalog.validators.validate_firstname_length], verbose_name='First name')),
                ('lastname', models.CharField(max_length=100, validators=[catalog.validators.validate_lastname_length], verbose_name='Last name')),
                ('username', models.CharField(max_length=25, validators=[catalog.validators.validate_username_length, catalog.validators.validate_username_alphadigits], verbose_name='User name')),
                ('password1', models.CharField(max_length=30, validators=[catalog.validators.validate_password_length, catalog.validators.validate_password_digit, catalog.validators.validate_password_uppercase])),
                ('password2', models.CharField(max_length=30)),
                ('birth_date', models.DateField(verbose_name='What is your birth date?')),
                ('gender', models.CharField(max_length=6)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15, validators=[catalog.validators.validate_phonenumber])),
                ('location', models.CharField(max_length=100)),
            ],
        ),
    ]
