# Generated by Django 3.0.5 on 2022-07-03 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_siteuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower',
            name='book_id',
            field=models.UUIDField(default=True, help_text='Unique ID for this particular book across whole library'),
        ),
    ]
