# Generated by Django 3.0.5 on 2022-07-04 15:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_auto_20220703_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='book_id',
            field=models.UUIDField(default=uuid.uuid5, help_text='Unique ID for this particular book across whole library'),
        ),
    ]
