# Generated by Django 3.0.5 on 2022-07-04 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_auto_20220704_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='book_id',
        ),
    ]
