# Generated by Django 3.0.5 on 2022-07-04 15:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_remove_payment_book_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrower',
            name='book_id',
        ),
        migrations.AddField(
            model_name='payment',
            name='book_id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular book across whole library'),
        ),
    ]
