# Generated by Django 3.0.5 on 2022-07-04 15:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0024_auto_20220704_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrower',
            name='book_id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular book across whole library'),
        ),
    ]
