# Generated by Django 3.0.5 on 2022-07-08 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0025_borrower_book_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower',
            name='date_borrowed',
            field=models.DateField(auto_now=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='expected_date_return',
            field=models.DateField(auto_now=True, max_length=120),
        ),
    ]
